version: "3.9"
services:
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
      - node.name=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=password"
    ports:
      - "9200:9200"

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER : minioadmin
      MINIO_ROOT_PASSWORD : minioadmin
    volumes:
      - "/data"
    command: server --console-address ":9001" /data
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  miniomc:
    image: miniomc-create-bucket
    build: .
    depends_on:
      - minio
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 2

  unique-file-service1:
    image: rtambunio/unique-file-service
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
      - "SERVER_PORT=8081"
    ports:
      - "8081:8081"
    depends_on:
      - miniomc
      - elastic-search
    deploy:
      mode: replicated
      replicas: 1

#  unique-file-service2:
#    image: rtambunio/unique-file-service
#    environment:
#      - "SPRING_PROFILES_ACTIVE=local"
#      - "SERVER_PORT=8081"
#    depends_on:
#      - miniomc
#      - elastic-search